// proyecto-frontend/src/app/components/contenido-apunte/contenido-apunte.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges, ViewChildren, QueryList, ElementRef, AfterViewChecked, ViewChild } from '@angular/core';
import { Tema, TemaService } from '../../services/tema.service';
import { Apunte } from '../../services/apunte.service';

@Component({
  selector: 'app-contenido-apunte',
  standalone: false,
  templateUrl: './contenido-apunte.component.html',
  styleUrl: './contenido-apunte.component.css'
})
export class ContenidoApunteComponent implements OnInit, OnChanges, AfterViewChecked {
  modalVisible = false;
  modalTitulo = '';
  modalMensaje = '';
  temaPendiente?: Tema;
  modoLectura: boolean = true;

  @Input() apunte!: Apunte;

  temas: Tema[] = [];
  nuevoTema: string = '';

  editandoId: number | null = null;
  nombreTemporal: string = '';
  nuevoSubtemaPadreId: number | null = null;
  inputFocused = false;

  @ViewChildren('inputEditarRef') inputsEditar!: QueryList<ElementRef>;
  @ViewChild('inputNuevoSubtema') inputNuevoSubtema!: ElementRef;

  constructor(private temaService: TemaService) { }

  ngOnInit(): void {
    this.cargarTemas();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['apunte'] && !changes['apunte'].firstChange) {
      this.cargarTemas();
    }
  }

  alternarModo(): void {
    this.modoLectura = !this.modoLectura;
  }

  ngAfterViewChecked(): void {
    if (this.editandoId !== null && !this.inputFocused) {
      setTimeout(() => {
        if (this.inputsEditar && this.inputsEditar.length > 0) {
          const inputEl = this.inputsEditar.find(el => {
            const nativeEl = el?.nativeElement as HTMLInputElement;
            return nativeEl?.value === this.nombreTemporal;
          });

          if (inputEl?.nativeElement) {
            const input = inputEl.nativeElement as HTMLInputElement;
            input.focus();
            input.setSelectionRange(input.value.length, input.value.length);
            this.inputFocused = true;
          }
        }
      }, 0);
    }

    if (this.nuevoSubtemaPadreId !== null) {
      setTimeout(() => {
        if (this.inputNuevoSubtema?.nativeElement) {
          this.inputNuevoSubtema.nativeElement.focus();
        }
      }, 0);
    }
  }

  cargarTemas(): void {
    this.temaService.listarTemas(this.apunte.idApunte).subscribe({
      next: data => this.temas = data,
      error: err => console.error('Error al cargar temas:', err)
    });
  }

  get temasPadre(): Tema[] {
    return this.temas.filter(t => t.idTemaPadre == null);
  }

  obtenerSubtemas(padre: Tema): Tema[] {
    return this.temas.filter(t => Number(t.idTemaPadre) === padre.idTema);
  }

  agregarTema(): void {
    const nombre = this.nuevoTema.trim();
    if (!nombre) return;

    const nuevo: Partial<Tema> = {
      nombre,
      idApunte: this.apunte.idApunte,
      idTemaPadre: null
    };

    this.temaService.insertarTema(nuevo).subscribe({
      next: tema => {
        this.temas.push(tema);
        this.nuevoTema = '';
      },
      error: err => console.error('Error al agregar tema:', err)
    });
  }

  agregarSubtema(padre: Tema): void {
    this.nuevoSubtemaPadreId = padre.idTema;
    this.editandoId = -1;
    this.nombreTemporal = '';
  }

  guardarNuevoSubtema(padre: Tema): void {
    const nombre = this.nombreTemporal.trim();
    if (!nombre) {
      this.cancelarNuevoSubtema();
      return;
    }

    const nuevo: Partial<Tema> = {
      nombre,
      idApunte: this.apunte.idApunte,
      idTemaPadre: padre.idTema
    };

    this.temaService.insertarTema(nuevo).subscribe({
      next: tema => {
        this.temas.push(tema);
        this.nuevoSubtemaPadreId = null;
        this.editandoId = null;
      },
      error: err => console.error('Error al insertar subtema:', err)
    });
  }

  cancelarNuevoSubtema(): void {
    this.nuevoSubtemaPadreId = null;
    this.editandoId = null;
    this.nombreTemporal = '';
  }

  habilitarEdicion(tema: Tema): void {
    this.editandoId = tema.idTema;
    this.nombreTemporal = tema.nombre;
    this.inputFocused = false;
  }

  guardarEdicion(tema: Tema): void {
    const nuevoNombre = this.nombreTemporal.trim();
    if (!nuevoNombre) return;

    const actualizado = { ...tema, nombre: nuevoNombre };

    this.temaService.modificarTema(actualizado).subscribe({
      next: () => {
        tema.nombre = nuevoNombre;
        this.editandoId = null;
      },
      error: err => console.error('Error al actualizar tema:', err)
    });
  }

  cancelarEdicion(): void {
    this.editandoId = null;
  }

  eliminarTema(tema: Tema): void {
    this.temaPendiente = tema;
    this.modalTitulo = 'Confirmar eliminación';
    this.modalMensaje = '¿Estás seguro de eliminar este tema? También se eliminarán sus contenidos y subtemas.';
    this.modalVisible = true;
  }

  confirmarEliminacionTema(): void {
    if (!this.temaPendiente) return;

    this.temaService.eliminarTema(this.temaPendiente.idTema).subscribe({
      next: () => {
        this.temas = this.temas.filter(
          t => t.idTema !== this.temaPendiente?.idTema && t.idTemaPadre !== this.temaPendiente?.idTema
        );
        this.temaPendiente = undefined;
        this.modalVisible = false;
      },
      error: err => console.error('Error al eliminar tema:', err)
    });
  }

  cancelarEliminacionTema(): void {
    this.modalVisible = false;
    this.temaPendiente = undefined;
  }
}
<div class="contenido-apunte-container">

  <!-- BOTÓN DE MODO -->
  <div class="modo-toggle-container">
    <button
      class="modo-toggle-btn"
      [ngClass]="modoLectura ? 'modo-lectura' : 'modo-edicion'"
      (click)="alternarModo()">
      {{ modoLectura ? 'Modo Lectura' : 'Modo Edición' }}
    </button>
  </div>

  <!-- Campo NUEVO TEMA PADRE -->
  <div class="formulario-tema" *ngIf="!modoLectura">
    <input
      type="text"
      class="input-tema"
      placeholder="Nuevo tema padre (Enter para añadir)"
      [(ngModel)]="nuevoTema"
      (keydown.enter)="agregarTema()"
    />
  </div>

  <!-- Renderizar los temas padres recursivamente -->
  <ng-container *ngFor="let tema of temasPadre">
    <ng-container *ngTemplateOutlet="renderTema; context: { $implicit: tema, nivel: 0 }"></ng-container>
  </ng-container>

  <!-- Plantilla recursiva -->
  <ng-template #renderTema let-tema let-nivel="nivel">
    <div class="bloque-tema" [style.marginLeft.px]="nivel * 20">
      <!-- Edición -->
      <div *ngIf="editandoId === tema.idTema; else verTitulo">
        <input
          #inputEditarRef
          [(ngModel)]="nombreTemporal"
          (keydown.enter)="guardarEdicion(tema)"
          (keydown.escape)="cancelarEdicion()"
          (blur)="guardarEdicion(tema)"
          class="input-tema"
        />
      </div>

      <ng-template #verTitulo>
        <div class="titulo-tema">
          <span (click)="!modoLectura && habilitarEdicion(tema)">{{ tema.nombre }}</span>
          <span *ngIf="!modoLectura">
            <button class="btn-subtema" (click)="agregarSubtema(tema); $event.stopPropagation()">➕</button>
            <button class="btn-eliminar" (click)="eliminarTema(tema); $event.stopPropagation()">🗑️</button>
          </span>
        </div>
      </ng-template>

      <app-contenido-tema [tema]="tema" [modoLectura]="modoLectura"></app-contenido-tema>

      <!-- Nuevo subtema -->
      <div *ngIf="!modoLectura && nuevoSubtemaPadreId === tema.idTema" class="subtema">
        <input
          #inputNuevoSubtema
          class="input-tema"
          [(ngModel)]="nombreTemporal"
          (keydown.enter)="guardarNuevoSubtema(tema)"
          (keydown.escape)="cancelarNuevoSubtema()"
          (blur)="cancelarNuevoSubtema()"
          placeholder="Nuevo subtema..."
        />
      </div>

      <!-- Subtemas recursivos -->
      <ng-container *ngFor="let sub of obtenerSubtemas(tema)">
        <ng-container *ngTemplateOutlet="renderTema; context: { $implicit: sub, nivel: nivel + 1 }"></ng-container>
      </ng-container>
    </div>
  </ng-template>
</div>

<app-modal-confirmacion
  [visible]="modalVisible"
  [titulo]="modalTitulo"
  [mensaje]="modalMensaje"
  (aceptar)="confirmarEliminacionTema()"
  (cancelar)="cancelarEliminacionTema()">
</app-modal-confirmacion>

// proyecto-frontend/react-notes/src/components/ContenidoApunte.tsx
import React, { useEffect, useRef, useState } from "react";
import { ContenidoTema } from "./ContenidoTema";
import { ModalConfirmacion } from "./ModalConfirmacion";
import "./ContenidoApunte.css";
import {
  listarTemas,
  insertarTema,
  modificarTema,
  eliminarTema
} from "../api/temas.api";

/* =======================
   Interfaces
======================= */
interface Tema {
  idTema: number;
  idApunte: number;
  idTemaPadre: number | null;
  nombre: string;
}

interface Apunte {
  idApunte: number;
}

interface Props {
  apunte: Apunte;
}

/* =======================
   Componente principal
======================= */
export function ContenidoApunte({ apunte }: Props) {
  const [temas, setTemas] = useState<Tema[]>([]);
  const [nuevoTema, setNuevoTema] = useState("");
  const [modoLectura, setModoLectura] = useState(true);

  const [editandoId, setEditandoId] = useState<number | null>(null);
  const [nombreTemporal, setNombreTemporal] = useState("");

  const [nuevoSubtemaPadreId, setNuevoSubtemaPadreId] =
    useState<number | null>(null);

  const [modalVisible, setModalVisible] = useState(false);
  const [temaPendiente, setTemaPendiente] = useState<Tema | null>(null);

  const inputEditarRef = useRef<HTMLInputElement | null>(null);
  const inputNuevoSubtemaRef = useRef<HTMLInputElement | null>(null);

  /* ===== Cargar temas ===== */
  useEffect(() => {
    if (!apunte?.idApunte) return;

    listarTemas(apunte.idApunte)
      .then(setTemas)
      .catch(err => console.error("Error al cargar temas:", err));
  }, [apunte]);

  /* ===== Foco automático ===== */
  useEffect(() => {
    if (editandoId !== null && inputEditarRef.current) {
      inputEditarRef.current.focus();
      inputEditarRef.current.setSelectionRange(
        inputEditarRef.current.value.length,
        inputEditarRef.current.value.length
      );
    }
  }, [editandoId]);

  useEffect(() => {
    if (nuevoSubtemaPadreId !== null && inputNuevoSubtemaRef.current) {
      inputNuevoSubtemaRef.current.focus();
    }
  }, [nuevoSubtemaPadreId]);

  /* ===== Helpers ===== */
  const temasPadre = temas.filter(t => t.idTemaPadre === null);
  const obtenerSubtemas = (padre: Tema) =>
    temas.filter(t => Number(t.idTemaPadre) === padre.idTema);

  const alternarModo = () => setModoLectura(!modoLectura);

  /* ===== CRUD ===== */
  const agregarTema = async () => {
    if (!nuevoTema.trim()) return;

    const tema = await insertarTema({
      nombre: nuevoTema.trim(),
      idApunte: apunte.idApunte,
      idTemaPadre: null
    });

    setTemas([...temas, tema]);
    setNuevoTema("");
  };

  const agregarSubtema = (padre: Tema) => {
    setNuevoSubtemaPadreId(padre.idTema);
    setEditandoId(-1);
    setNombreTemporal("");
  };

  const guardarNuevoSubtema = async (padre: Tema) => {
    if (!nombreTemporal.trim()) {
      cancelarNuevoSubtema();
      return;
    }

    const tema = await insertarTema({
      nombre: nombreTemporal.trim(),
      idApunte: apunte.idApunte,
      idTemaPadre: padre.idTema
    });

    setTemas([...temas, tema]);
    cancelarNuevoSubtema();
  };

  const cancelarNuevoSubtema = () => {
    setNuevoSubtemaPadreId(null);
    setEditandoId(null);
    setNombreTemporal("");
  };

  const habilitarEdicion = (tema: Tema) => {
    if (modoLectura) return;
    setEditandoId(tema.idTema);
    setNombreTemporal(tema.nombre);
  };

  const guardarEdicion = async (tema: Tema) => {
    if (!nombreTemporal.trim()) return;

    await modificarTema({ ...tema, nombre: nombreTemporal.trim() });
    setTemas(
      temas.map(t =>
        t.idTema === tema.idTema
          ? { ...t, nombre: nombreTemporal.trim() }
          : t
      )
    );
    setEditandoId(null);
  };

  /* ===== ELIMINACIÓN CON MODAL ===== */
  const confirmarEliminar = (tema: Tema) => {
    setTemaPendiente(tema);
    setModalVisible(true);
  };

  const eliminarConfirmado = async () => {
    if (!temaPendiente) return;

    await eliminarTema(temaPendiente.idTema);
    setTemas(
      temas.filter(
        t =>
          t.idTema !== temaPendiente.idTema &&
          t.idTemaPadre !== temaPendiente.idTema
      )
    );
    setTemaPendiente(null);
    setModalVisible(false);
  };

  /* ===== Render ===== */
  return (
    <div className="contenido-apunte-container">
      {/* BOTÓN MODO */}
      <div className="modo-toggle-container">
        <button
          className={`modo-toggle-btn ${
            modoLectura ? "modo-lectura" : "modo-edicion"
          }`}
          onClick={alternarModo}
        >
          {modoLectura ? "Modo Lectura" : "Modo Edición"}
        </button>
      </div>

      {/* NUEVO TEMA PADRE */}
      {!modoLectura && (
        <div className="formulario-tema">
          <input
            className="input-tema"
            placeholder="Nuevo tema padre (Enter para añadir)"
            value={nuevoTema}
            onChange={e => setNuevoTema(e.target.value)}
            onKeyDown={e => e.key === "Enter" && agregarTema()}
          />
        </div>
      )}

      {/* TEMAS */}
      {temasPadre.map(tema => (
        <TemaItem
          key={tema.idTema}
          tema={tema}
          nivel={0}
          obtenerSubtemas={obtenerSubtemas}
          modoLectura={modoLectura}
          editandoId={editandoId}
          nombreTemporal={nombreTemporal}
          setNombreTemporal={setNombreTemporal}
          habilitarEdicion={habilitarEdicion}
          guardarEdicion={guardarEdicion}
          agregarSubtema={agregarSubtema}
          confirmarEliminar={confirmarEliminar}
          nuevoSubtemaPadreId={nuevoSubtemaPadreId}
          guardarNuevoSubtema={guardarNuevoSubtema}
          cancelarNuevoSubtema={cancelarNuevoSubtema}
          inputEditarRef={inputEditarRef}
          inputNuevoSubtemaRef={inputNuevoSubtemaRef}
        />
      ))}

      {/* MODAL CONFIRMACIÓN */}
      <ModalConfirmacion
        visible={modalVisible}
        titulo="Eliminar tema"
        mensaje="¿Eliminar este tema y todos sus subtemas?"
        onAceptar={eliminarConfirmado}
        onCancelar={() => setModalVisible(false)}
      />
    </div>
  );
}

/* =======================
   Componente recursivo
======================= */
interface TemaItemProps {
  tema: Tema;
  nivel: number;
  obtenerSubtemas: (t: Tema) => Tema[];
  modoLectura: boolean;
  editandoId: number | null;
  nombreTemporal: string;
  setNombreTemporal: (v: string) => void;
  habilitarEdicion: (t: Tema) => void;
  guardarEdicion: (t: Tema) => void;
  agregarSubtema: (t: Tema) => void;
  confirmarEliminar: (t: Tema) => void;
  nuevoSubtemaPadreId: number | null;
  guardarNuevoSubtema: (t: Tema) => void;
  cancelarNuevoSubtema: () => void;
  inputEditarRef: React.RefObject<HTMLInputElement | null>;
  inputNuevoSubtemaRef: React.RefObject<HTMLInputElement | null>;
}

function TemaItem({
  tema,
  nivel,
  obtenerSubtemas,
  modoLectura,
  editandoId,
  nombreTemporal,
  setNombreTemporal,
  habilitarEdicion,
  guardarEdicion,
  agregarSubtema,
  confirmarEliminar,
  nuevoSubtemaPadreId,
  guardarNuevoSubtema,
  cancelarNuevoSubtema,
  inputEditarRef,
  inputNuevoSubtemaRef
}: TemaItemProps) {
  return (
    <div className="bloque-tema" style={{ marginLeft: nivel * 20 }}>
      {editandoId === tema.idTema ? (
        <input
          ref={inputEditarRef}
          className="input-tema"
          value={nombreTemporal}
          onChange={e => setNombreTemporal(e.target.value)}
          onKeyDown={e => e.key === "Enter" && guardarEdicion(tema)}
          onBlur={() => guardarEdicion(tema)}
        />
      ) : (
        <div className="titulo-tema">
          <span onClick={() => habilitarEdicion(tema)}>
            {tema.nombre}
          </span>
          {!modoLectura && (
            <span>
              <button onClick={() => agregarSubtema(tema)}>➕</button>
              <button onClick={() => confirmarEliminar(tema)}>🗑️</button>
            </span>
          )}
        </div>
      )}

      {/* CONTENIDO */}
      <ContenidoTema tema={tema} modoLectura={modoLectura} />

      {/* SUBTEMA NUEVO */}
      {!modoLectura && nuevoSubtemaPadreId === tema.idTema && (
        <div className="subtema">
          <input
            ref={inputNuevoSubtemaRef}
            className="input-tema"
            value={nombreTemporal}
            onChange={e => setNombreTemporal(e.target.value)}
            onKeyDown={e => e.key === "Enter" && guardarNuevoSubtema(tema)}
            onBlur={cancelarNuevoSubtema}
            placeholder="Nuevo subtema..."
          />
        </div>
      )}

      {/* SUBTEMAS */}
      {obtenerSubtemas(tema).map(sub => (
        <TemaItem
          key={sub.idTema}
          tema={sub}
          nivel={nivel + 1}
          obtenerSubtemas={obtenerSubtemas}
          modoLectura={modoLectura}
          editandoId={editandoId}
          nombreTemporal={nombreTemporal}
          setNombreTemporal={setNombreTemporal}
          habilitarEdicion={habilitarEdicion}
          guardarEdicion={guardarEdicion}
          agregarSubtema={agregarSubtema}
          confirmarEliminar={confirmarEliminar}
          nuevoSubtemaPadreId={nuevoSubtemaPadreId}
          guardarNuevoSubtema={guardarNuevoSubtema}
          cancelarNuevoSubtema={cancelarNuevoSubtema}
          inputEditarRef={inputEditarRef}
          inputNuevoSubtemaRef={inputNuevoSubtemaRef}
        />
      ))}
    </div>
  );
}
