// proyecto-frontend/src/app/components/contenido-tema/contenido-tema.component.ts
import { Component, Input, OnInit, AfterViewChecked, ViewChildren, QueryList, ElementRef, ViewChild } from '@angular/core';
import { Contenido, ContenidoService } from '../../services/contenido.service';
import { Tema } from '../../services/tema.service';

@Component({
  selector: 'app-contenido-tema',
  standalone: false,
  templateUrl: './contenido-tema.component.html',
  styleUrl: './contenido-tema.component.css'
})
export class ContenidoTemaComponent implements OnInit, AfterViewChecked {
  @Input() tema!: Tema;
  @Input() modoLectura: boolean = true;
  contenidos: Contenido[] = [];
  nuevoContenido: string = '';
  mostrarNuevo = false;

  editandoId: number | null = null;
  textoTemporal: string = '';
  inputFocused: boolean = false;

  modalVisible: boolean = false;
  modalTitulo: string = '';
  modalMensaje: string = '';
  contenidoPendiente?: Contenido;

  @ViewChildren('inputEditarContenido') inputsEditar!: QueryList<ElementRef>;
  @ViewChild('nuevoContenidoInput') nuevoContenidoInput!: ElementRef;

  constructor(private contenidoService: ContenidoService) { }

  ngOnInit(): void {
    if (this.tema?.idTema) {
      this.cargarContenidos();
    }
  }

  ngAfterViewChecked(): void {
    if (this.editandoId !== null && !this.inputFocused) {
      setTimeout(() => {
        const textareaEl = this.inputsEditar?.find(
          el => (el.nativeElement as HTMLTextAreaElement).value === this.textoTemporal
        );
        if (textareaEl?.nativeElement) {
          const el = textareaEl.nativeElement as HTMLTextAreaElement;
          el.focus();
          el.setSelectionRange(el.value.length, el.value.length);
          this.inputFocused = true;
        }
      }, 0);
    }

    if (this.mostrarNuevo && this.nuevoContenidoInput?.nativeElement) {
      setTimeout(() => {
        this.nuevoContenidoInput?.nativeElement?.focus();
      }, 0);
    }
  }

  cargarContenidos(): void {
    this.contenidoService.listarContenidos(this.tema.idTema).subscribe({
      next: (data) => this.contenidos = data,
      error: (err) => console.error('Error al cargar contenidos:', err)
    });
  }

  mostrarInputNuevo(): void {
    if (!this.modoLectura) {
      this.mostrarNuevo = true;
      this.nuevoContenido = '';
    }
  }

  agregarContenido(): void {
    const texto = this.nuevoContenido.trim();
    if (!texto) {
      this.cancelarNuevoContenido();
      return;
    }

    const nuevo: Partial<Contenido> = {
      idTema: this.tema.idTema,
      texto
    };

    this.contenidoService.insertarContenido(nuevo).subscribe({
      next: (contenido) => {
        this.contenidos.push(contenido);
        this.nuevoContenido = '';
        this.mostrarNuevo = false;
      },
      error: (err) => console.error('Error al insertar contenido:', err)
    });
  }

  cancelarNuevoContenido(): void {
    this.nuevoContenido = '';
    this.mostrarNuevo = false;
  }

  eliminarContenido(idContenido: number): void {
    const contenido = this.contenidos.find(c => c.idContenido === idContenido);
    if (!contenido) return;

    this.contenidoPendiente = contenido;
    this.modalTitulo = 'Confirmar eliminación';
    this.modalMensaje = '¿Deseas eliminar este contenido? Esta acción no se puede deshacer.';
    this.modalVisible = true;
  }

  confirmarEliminacionContenido(): void {
    if (!this.contenidoPendiente) return;

    this.contenidoService.eliminarContenido(this.contenidoPendiente.idContenido).subscribe({
      next: () => {
        this.contenidos = this.contenidos.filter(c => c.idContenido !== this.contenidoPendiente?.idContenido);
        this.contenidoPendiente = undefined;
        this.modalVisible = false;
      },
      error: err => console.error('Error al eliminar contenido:', err)
    });
  }

  cancelarEliminacionContenido(): void {
    this.modalVisible = false;
    this.contenidoPendiente = undefined;
  }

  habilitarEdicion(c: Contenido): void {
    if (!this.modoLectura) {
      this.editandoId = c.idContenido;
      this.textoTemporal = c.texto;
      this.inputFocused = false;
    }
  }

  guardarEdicion(c: Contenido): void {
    const texto = this.textoTemporal.trim();
    if (!texto) return;

    const actualizado = { ...c, texto };

    this.contenidoService.modificarContenido(actualizado).subscribe({
      next: () => {
        c.texto = texto;
        this.editandoId = null;
      },
      error: (err) => console.error('Error al modificar contenido:', err)
    });
  }

  cancelarEdicion(): void {
    this.editandoId = null;
  }

  detectarTecla(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.agregarContenido();
    } else if (event.key === 'Escape') {
      this.cancelarNuevoContenido();
    }
  }

  blurNuevoContenido(): void {
    const texto = this.nuevoContenido.trim();
    if (texto) {
      this.agregarContenido();
    } else {
      this.cancelarNuevoContenido();
    }
  }

  detectarTeclaEdicion(event: KeyboardEvent, contenido: Contenido): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.guardarEdicion(contenido);
    } else if (event.key === 'Escape') {
      this.cancelarEdicion();
    }
  }

  ajustarAlturaTextarea(textarea: HTMLTextAreaElement): void {
    textarea.style.height = 'auto'; // reset altura
    textarea.style.height = textarea.scrollHeight + 'px'; // altura real del contenido
  }
}

<div class="contenido-tema-container">
  <!-- Entrada nueva tipo etiqueta -->
  <div *ngIf="!modoLectura && !mostrarNuevo" class="nuevo-texto-placeholder" (click)="mostrarInputNuevo()">
    Nuevo contenido...
  </div>

  <!-- Campo para nuevo contenido -->
  <textarea
    *ngIf="!modoLectura && mostrarNuevo"
    #nuevoContenidoInput
    [(ngModel)]="nuevoContenido"
    placeholder="Nuevo contenido..."
    (keydown)="detectarTecla($event)"
    (blur)="blurNuevoContenido()"
    (input)="ajustarAlturaTextarea(nuevoContenidoInput)"
    (focus)="ajustarAlturaTextarea(nuevoContenidoInput)"
    class="input-contenido"
  ></textarea>

  <!-- Lista de contenidos -->
  <ul *ngIf="contenidos.length > 0; else sinContenidos" class="lista-contenidos">
    <li *ngFor="let c of contenidos">
      <div *ngIf="editandoId === c.idContenido; else verContenido" class="edicion">
        <textarea
          #inputEditarContenido
          [(ngModel)]="textoTemporal"
          (keydown)="detectarTeclaEdicion($event, c)"
          (blur)="guardarEdicion(c)"
          (input)="ajustarAlturaTextarea(inputEditarContenido)"
          (focus)="ajustarAlturaTextarea(inputEditarContenido)"
          class="input-contenido"
        ></textarea>
      </div>

      <ng-template #verContenido>
        <div class="contenido-renderizado" (click)="habilitarEdicion(c)">
          {{ c.texto }}
        </div>
        <button *ngIf="!modoLectura" class="btn-eliminar" (click)="eliminarContenido(c.idContenido)">🗑️</button>
      </ng-template>
    </li>
  </ul>

  <ng-template #sinContenidos></ng-template>
</div>

<app-modal-confirmacion
  [visible]="modalVisible"
  [titulo]="modalTitulo"
  [mensaje]="modalMensaje"
  (aceptar)="confirmarEliminacionContenido()"
  (cancelar)="cancelarEliminacionContenido()">
</app-modal-confirmacion>

// proyecto-frontend/react-notes/src/components/ContenidoTema.tsx
import { useEffect, useRef, useState } from "react";
import "./ContenidoTema.css";
import {
  listarContenidos,
  insertarContenido,
  modificarContenido,
  eliminarContenido
} from "../api/contenidos.api";

/* =======================
   Interfaces
======================= */
interface Contenido {
  idContenido: number;
  idTema: number;
  texto: string;
}

interface Tema {
  idTema: number;
}

interface Props {
  tema: Tema;
  modoLectura: boolean;
}

/* =======================
   Componente
======================= */
export function ContenidoTema({ tema, modoLectura }: Props) {
  const [contenidos, setContenidos] = useState<Contenido[]>([]);
  const [nuevoContenido, setNuevoContenido] = useState("");
  const [mostrarNuevo, setMostrarNuevo] = useState(false);

  const [editandoId, setEditandoId] = useState<number | null>(null);
  const [textoTemporal, setTextoTemporal] = useState("");
  const [inputFocused, setInputFocused] = useState(false);

  const [modalVisible, setModalVisible] = useState(false);
  const [contenidoPendiente, setContenidoPendiente] =
    useState<Contenido | null>(null);

  const nuevoContenidoRef = useRef<HTMLTextAreaElement | null>(null);
  const editarContenidoRef = useRef<HTMLTextAreaElement | null>(null);

  /* ===== Cargar contenidos ===== */
  useEffect(() => {
    if (!tema?.idTema) return;

    listarContenidos(tema.idTema)
      .then(setContenidos)
      .catch(err => console.error(err));
  }, [tema]);

  /* ===== Foco automático ===== */
  useEffect(() => {
    if (editandoId !== null && editarContenidoRef.current && !inputFocused) {
      editarContenidoRef.current.focus();
      editarContenidoRef.current.setSelectionRange(
        editarContenidoRef.current.value.length,
        editarContenidoRef.current.value.length
      );
      setInputFocused(true);
    }

    if (mostrarNuevo && nuevoContenidoRef.current) {
      nuevoContenidoRef.current.focus();
    }
  }, [editandoId, mostrarNuevo, inputFocused]);

  /* ===== Helpers ===== */
  const ajustarAltura = (el: HTMLTextAreaElement) => {
    el.style.height = "auto";
    el.style.height = el.scrollHeight + "px";
  };

  /* ===== Acciones ===== */
  const mostrarInputNuevo = () => {
    if (!modoLectura) {
      setMostrarNuevo(true);
      setNuevoContenido("");
    }
  };

  const agregarContenido = async () => {
    const texto = nuevoContenido.trim();
    if (!texto) {
      cancelarNuevoContenido();
      return;
    }

    const contenido = await insertarContenido({
      idTema: tema.idTema,
      texto
    });

    setContenidos([...contenidos, contenido]);
    cancelarNuevoContenido();
  };

  const cancelarNuevoContenido = () => {
    setNuevoContenido("");
    setMostrarNuevo(false);
  };

  const habilitarEdicion = (c: Contenido) => {
    if (!modoLectura) {
      setEditandoId(c.idContenido);
      setTextoTemporal(c.texto);
      setInputFocused(false);
    }
  };

  const guardarEdicion = async (c: Contenido) => {
    const texto = textoTemporal.trim();
    if (!texto) return;

    await modificarContenido({ ...c, texto });
    setContenidos(
      contenidos.map(cont =>
        cont.idContenido === c.idContenido
          ? { ...cont, texto }
          : cont
      )
    );
    setEditandoId(null);
  };

  const confirmarEliminar = (c: Contenido) => {
    setContenidoPendiente(c);
    setModalVisible(true);
  };

  const eliminarConfirmado = async () => {
    if (!contenidoPendiente) return;

    await eliminarContenido(contenidoPendiente.idContenido);
    setContenidos(
      contenidos.filter(c => c.idContenido !== contenidoPendiente.idContenido)
    );
    setContenidoPendiente(null);
    setModalVisible(false);
  };

  return (
    <div className="contenido-tema-container">
      {/* NUEVO */}
      {!modoLectura && !mostrarNuevo && (
        <div className="nuevo-texto-placeholder" onClick={mostrarInputNuevo}>
          Nuevo contenido...
        </div>
      )}

      {/* INPUT NUEVO */}
      {!modoLectura && mostrarNuevo && (
        <textarea
          ref={nuevoContenidoRef}
          className="input-contenido"
          value={nuevoContenido}
          placeholder="Nuevo contenido..."
          onChange={e => setNuevoContenido(e.target.value)}
          onKeyDown={e => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              agregarContenido();
            } else if (e.key === "Escape") {
              cancelarNuevoContenido();
            }
          }}
          onBlur={agregarContenido}
          onInput={e => ajustarAltura(e.currentTarget)}
          onFocus={e => ajustarAltura(e.currentTarget)}
        />
      )}

      {/* LISTA */}
      <ul className="lista-contenidos">
        {contenidos.map(c => (
          <li key={c.idContenido}>
            {editandoId === c.idContenido ? (
              <textarea
                ref={editarContenidoRef}
                className="input-contenido"
                value={textoTemporal}
                onChange={e => setTextoTemporal(e.target.value)}
                onKeyDown={e => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    guardarEdicion(c);
                  } else if (e.key === "Escape") {
                    setEditandoId(null);
                  }
                }}
                onBlur={() => guardarEdicion(c)}
                onInput={e => ajustarAltura(e.currentTarget)}
                onFocus={e => ajustarAltura(e.currentTarget)}
              />
            ) : (
              <>
                <div
                  className="contenido-renderizado"
                  onClick={() => habilitarEdicion(c)}
                >
                  {c.texto}
                </div>
                {!modoLectura && (
                  <button
                    className="btn-eliminar"
                    onClick={() => confirmarEliminar(c)}
                  >
                    🗑️
                  </button>
                )}
              </>
            )}
          </li>
        ))}
      </ul>

      {/* MODAL */}
      {modalVisible && (
        <div className="modal-confirmacion">
          <p>¿Deseas eliminar este contenido?</p>
          <button onClick={eliminarConfirmado}>Aceptar</button>
          <button onClick={() => setModalVisible(false)}>Cancelar</button>
        </div>
      )}
    </div>
  );
}
