// proyecto-frontend/src/app/components/modal-confirmacion/modal-confirmacion.component.ts
import { Component, Input, Output, EventEmitter, HostListener } from '@angular/core';

@Component({
  selector: 'app-modal-confirmacion',
  standalone: false,
  templateUrl: './modal-confirmacion.component.html',
  styleUrl: './modal-confirmacion.component.css'
})
export class ModalConfirmacionComponent {
  @Input() visible: boolean = false;
  @Input() mensaje: string = '¿Estás seguro que deseas continuar?';
  @Input() titulo: string = 'Confirmación';

  @Output() aceptar = new EventEmitter<void>();
  @Output() cancelar = new EventEmitter<void>();

  confirmar(): void {
    this.aceptar.emit();
  }

  cerrar(): void {
    this.cancelar.emit();
  }

  // ✅ Captura de teclas cuando el modal está activo
  @HostListener('document:keydown', ['$event'])
  manejarTeclas(event: KeyboardEvent): void {
    if (!this.visible) return;

    if (event.key === 'Enter') {
      event.preventDefault();
      this.confirmar();
    } else if (event.key === 'Escape') {
      event.preventDefault();
      this.cerrar();
    }
  }
}
<div class="modal-overlay" *ngIf="visible">
  <div class="modal-content">
    <h4>{{ titulo }}</h4>
    <p>{{ mensaje }}</p>
    <div class="modal-botones">
      <button class="btn-confirmar" (click)="confirmar()">Aceptar</button>
      <button class="btn-cancelar" (click)="cerrar()">Cancelar</button>
    </div>
  </div>
</div>

// proyecto-frontend/react-notes/src/components/ModalConfirmacion.tsx
import { useEffect } from "react";
import "./ModalConfirmacion.css";

interface Props {
  visible: boolean;
  titulo?: string;
  mensaje?: string;
  onAceptar: () => void;
  onCancelar: () => void;
}

export function ModalConfirmacion({
  visible,
  titulo = "Confirmación",
  mensaje = "¿Estás seguro que deseas continuar?",
  onAceptar,
  onCancelar
}: Props) {

  // ⌨️ Manejo de teclas (Enter / Escape)
  useEffect(() => {
    if (!visible) return;

    const manejarTeclas = (e: KeyboardEvent) => {
      if (e.key === "Enter") {
        e.preventDefault();
        onAceptar();
      } else if (e.key === "Escape") {
        e.preventDefault();
        onCancelar();
      }
    };

    document.addEventListener("keydown", manejarTeclas);
    return () => document.removeEventListener("keydown", manejarTeclas);
  }, [visible, onAceptar, onCancelar]);

  if (!visible) return null;

  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <h4>{titulo}</h4>
        <p>{mensaje}</p>
        <div className="modal-botones">
          <button className="btn-confirmar" onClick={onAceptar}>
            Aceptar
          </button>
          <button className="btn-cancelar" onClick={onCancelar}>
            Cancelar
          </button>
        </div>
      </div>
    </div>
  );
}
