// proyecto-frontend/react-reminders/src/components/Actividades.tsx
import { useEffect, useState } from "react";
import "./Actividades.css";
import {
  getRecordatorios,
  eliminarRecordatorio
} from "../api/recordatorios.api";
import { ModalConfirmacion } from "./ModalConfirmacion";
import { FormRecordatorio } from "./FormRecordatorio";

interface Recordatorio {
  idRecordatorio: number;
  fechaLimite: string;
  hora: string;
  titulo: string;
  descripcion: string;
  estado: string;
}

export function Actividades() {
  const [recordatoriosAgrupados, setRecordatoriosAgrupados] = useState<Record<string, Recordatorio[]>>({});
  const [filtroSeleccionado, setFiltroSeleccionado] = useState("7");
  const [menuAbierto, setMenuAbierto] = useState<number | null>(null);

  const [modoFormulario, setModoFormulario] = useState<"crear" | "editar" | null>(null);
  const [recordatorioEditando, setRecordatorioEditando] = useState<Recordatorio | null>(null);

  const [pendienteEliminar, setPendienteEliminar] = useState<Recordatorio | null>(null);

  /* =======================
     CARGA Y FILTROS
  ======================= */
  useEffect(() => {
    cargarRecordatorios();
  }, [filtroSeleccionado]);

  const cargarRecordatorios = async () => {
    const hoy = new Date();
    hoy.setHours(0, 0, 0, 0);

    let recordatorios: Recordatorio[] = await getRecordatorios();

    // Solo activos
    recordatorios = recordatorios.filter(r => r.estado === "Activo");

    if (filtroSeleccionado === "7" || filtroSeleccionado === "30") {
      const dias = Number(filtroSeleccionado);
      const fechaLimite = new Date(hoy);
      fechaLimite.setDate(hoy.getDate() + dias);

      recordatorios = recordatorios.filter(r => {
        const fecha = new Date(r.fechaLimite);
        return fecha >= hoy && fecha <= fechaLimite;
      });
    }

    if (filtroSeleccionado === "atrasadas") {
      recordatorios = recordatorios.filter(r => {
        const fecha = new Date(r.fechaLimite);
        return fecha < hoy;
      });
    }

    setRecordatoriosAgrupados(agruparPorFecha(recordatorios));
  };

  const agruparPorFecha = (recordatorios: Recordatorio[]) => {
    return recordatorios.reduce((acc, r) => {
      const fecha = r.fechaLimite;
      acc[fecha] = acc[fecha] || [];
      acc[fecha].push(r);
      return acc;
    }, {} as Record<string, Recordatorio[]>);
  };

  const fechasOrdenadas = Object.keys(recordatoriosAgrupados).sort(
    (a, b) => new Date(a).getTime() - new Date(b).getTime()
  );

  /* =======================
     MENÚ CONTEXTUAL
  ======================= */
  useEffect(() => {
    const cerrarMenu = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest(".menu-opciones") && !target.closest(".menu-btn")) {
        setMenuAbierto(null);
      }
    };

    document.addEventListener("click", cerrarMenu);
    return () => document.removeEventListener("click", cerrarMenu);
  }, []);

  /* =======================
     FORMULARIO
  ======================= */
  if (modoFormulario) {
    return (
      <FormRecordatorio
        modo={modoFormulario}
        recordatorio={recordatorioEditando}
        onCancelar={() => {
          setModoFormulario(null);
          setRecordatorioEditando(null);
        }}
        onGuardado={() => {
          setModoFormulario(null);
          setRecordatorioEditando(null);
          cargarRecordatorios();
        }}
      />
    );
  }

  /* =======================
     RENDER
  ======================= */
  return (
    <div className="area-personal-container">
      <h2 className="titulo">Área personal</h2>

      <div className="contenido-linea-tiempo">
        <div className="encabezado-linea-tiempo">
          <h3 className="subtitulo">Línea de tiempo</h3>

          <div className="filtros">
            <button
              className="btn-agregar"
              onClick={() => setModoFormulario("crear")}
            >
              + Añadir recordatorio
            </button>

            <select
              value={filtroSeleccionado}
              onChange={e => setFiltroSeleccionado(e.target.value)}
            >
              <option value="todas">Todas</option>
              <option value="atrasadas">Atrasadas</option>
              <option value="7">Próximos 7 días</option>
              <option value="30">Próximos 30 días</option>
            </select>
          </div>
        </div>

        {fechasOrdenadas.map(fecha => (
          <div key={fecha} className="grupo-fecha">
            <h4 className="fecha">
              {new Date(fecha).toLocaleDateString("es-EC", {
                weekday: "long",
                year: "numeric",
                month: "long",
                day: "numeric"
              })}
            </h4>

            {recordatoriosAgrupados[fecha].map(r => (
              <div key={r.idRecordatorio} className="item-recordatorio">
                <div className="hora-icono">
                  <span className="hora">{r.hora}</span>
                </div>

                <div className="detalle-recordatorio">
                  <div className="titulo-recordatorio">{r.titulo}</div>
                  <div className="descripcion">{r.descripcion}</div>
                </div>

                <div className="acciones">
                  <button
                    className="menu-btn"
                    onClick={() =>
                      setMenuAbierto(
                        menuAbierto === r.idRecordatorio
                          ? null
                          : r.idRecordatorio
                      )
                    }
                  >
                    ⋮
                  </button>

                  {menuAbierto === r.idRecordatorio && (
                    <div className="menu-opciones">
                      <button
                        onClick={() => {
                          setRecordatorioEditando(r);
                          setModoFormulario("editar");
                        }}
                      >
                        Modificar
                      </button>
                      <button onClick={() => setPendienteEliminar(r)}>
                        Eliminar
                      </button>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>

      <ModalConfirmacion
        visible={!!pendienteEliminar}
        titulo="Eliminar recordatorio"
        mensaje="¿Deseas eliminar este recordatorio?"
        onAceptar={async () => {
          if (!pendienteEliminar) return;
          await eliminarRecordatorio(pendienteEliminar.idRecordatorio);
          setPendienteEliminar(null);
          cargarRecordatorios();
        }}
        onCancelar={() => setPendienteEliminar(null)}
      />
    </div>
  );
}

// proyecto-frontend/src/app/components/actividades/actividades.component.ts
import { Component, OnInit, ElementRef, HostListener } from '@angular/core';
import { Recordatorio, RecordatorioService } from '../../services/recordatorio.service';
import { Router } from '@angular/router';
import { MatSnackBar } from '@angular/material/snack-bar';

@Component({
  selector: 'app-actividades',
  standalone: false,
  templateUrl: './actividades.component.html',
  styleUrl: './actividades.component.css'
})
export class ActividadesComponent implements OnInit {
  recordatoriosAgrupados: { [fecha: string]: Recordatorio[] } = {};
  filtroSeleccionado: string = '7';
  menuAbierto: number | null = null;

  constructor(private recordatorioService: RecordatorioService, private router: Router, private snackBar: MatSnackBar) { }

  ngOnInit(): void {
    this.cargarRecordatorios();
  }

  aplicarFiltro(): void {
    this.cargarRecordatorios();
  }

  cargarRecordatorios(): void {
    const hoy = new Date();
    hoy.setHours(0, 0, 0, 0);

    this.recordatorioService.getRecordatorios().subscribe(recordatorios => {
      // Filtrar solo activos
      recordatorios = recordatorios.filter(r => r.estado === 'Activo');

      if (this.filtroSeleccionado === '7') {
        const fechaLimite = new Date(hoy);
        fechaLimite.setDate(hoy.getDate() + 7);
        recordatorios = recordatorios.filter(r => {
          const fecha = new Date(r.fechaLimite);
          return fecha >= hoy && fecha <= fechaLimite;
        });
      } else if (this.filtroSeleccionado === '30') {
        const fechaLimite = new Date(hoy);
        fechaLimite.setDate(hoy.getDate() + 30);
        recordatorios = recordatorios.filter(r => {
          const fecha = new Date(r.fechaLimite);
          return fecha >= hoy && fecha <= fechaLimite;
        });
      } else if (this.filtroSeleccionado === 'atrasadas') {
        recordatorios = recordatorios.filter(r => {
          const fecha = new Date(r.fechaLimite);
          return fecha < hoy;
        });
      }

      this.recordatoriosAgrupados = this.agruparPorFecha(recordatorios);
    });
  }

  agruparPorFecha(recordatorios: Recordatorio[]): { [fecha: string]: Recordatorio[] } {
    return recordatorios.reduce((acc, r) => {
      const fecha = r.fechaLimite;
      acc[fecha] = acc[fecha] || [];
      acc[fecha].push(r);
      return acc;
    }, {} as { [fecha: string]: Recordatorio[] });
  }

  get fechasOrdenadas(): string[] {
    return Object.keys(this.recordatoriosAgrupados).sort((a, b) => new Date(a).getTime() - new Date(b).getTime());
  }

  toggleMenu(id: number): void {
    this.menuAbierto = this.menuAbierto === id ? null : id;
  }

  abrirFormulario(): void {
    this.router.navigate(['/recordatorio'], { state: { modo: 'crear' } });
  }

  modificarRecordatorio(recordatorio: Recordatorio): void {
    this.router.navigate(['/recordatorio'], { state: { modo: 'editar', recordatorio } });
  }

  eliminarRecordatorio(id: number): void {
    this.recordatorioService.eliminarRecordatorio(id).subscribe({
      next: () => {
        this.snackBar.open('Recordatorio eliminado correctamente', 'Cerrar', {
          duration: 3000,
          horizontalPosition: 'center',
          verticalPosition: 'bottom',
          panelClass: ['snackbar-success']
        });
        this.cargarRecordatorios();
      },
      error: () => {
        this.snackBar.open('Error al eliminar recordatorio', 'Cerrar', {
          duration: 3000,
          panelClass: ['snackbar-error'],
          horizontalPosition: 'center',
          verticalPosition: 'bottom'
        });
      }
    });
  }

  @HostListener('document:click', ['$event'])
  onClickOutside(event: MouseEvent): void {
    const target = event.target as HTMLElement;

    // Si el clic no ocurre dentro de un .menu-opciones o .menu-btn, cierra el menú
    if (!target.closest('.menu-opciones') && !target.closest('.menu-btn')) {
      this.menuAbierto = null;
    }
  }
}
<div class="area-personal-container">
  <h2 class="titulo">Área personal</h2>

  <div class="contenido-linea-tiempo">
    <div class="encabezado-linea-tiempo">
      <h3 class="subtitulo">Línea de tiempo</h3>
      <div class="filtros">
        <button class="btn-agregar" (click)="abrirFormulario()">+ Añadir recordatorio</button>
        <select [(ngModel)]="filtroSeleccionado" (change)="aplicarFiltro()">
          <option value="todas">Todas</option>
          <option value="atrasadas">Atrasadas</option>
          <option value="7">Próximos 7 días</option>
          <option value="30">Próximos 30 días</option>
        </select>
      </div>
    </div>

    <div *ngFor="let fecha of fechasOrdenadas" class="grupo-fecha">
      <h4 class="fecha">{{ fecha | date:'fullDate':'':'es-EC' }}</h4>

      <div *ngFor="let r of recordatoriosAgrupados[fecha]" class="item-recordatorio">
        <div class="hora-icono">
          <span class="hora">{{ r.hora }}</span>
        </div>
        <div class="detalle-recordatorio">
          <div class="titulo-recordatorio">{{ r.titulo }}</div>
          <div class="descripcion">{{ r.descripcion }}</div>
        </div>
        <div class="acciones">
          <button class="menu-btn" (click)="toggleMenu(r.idRecordatorio)">⋮</button>
          <div class="menu-opciones" *ngIf="menuAbierto === r.idRecordatorio">
            <button (click)="modificarRecordatorio(r)">Modificar</button>
            <button (click)="eliminarRecordatorio(r.idRecordatorio)">Eliminar</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
