// proyecto-frontend/react-notes/src/components/CuadernoVirtual.tsx
import { useEffect, useState } from "react";
import { ContenidoApunte } from "./ContenidoApunte";
import "./CuadernoVirtual.css";
import { listarApuntes, insertarApunte, modificarApunte, eliminarApunte } from "../api/apuntes.api";

interface Apunte {
  idApunte: number;
  titulo: string;
  resumen?: string;
}

interface Props {
  idMateria: number;
}

export function CuadernoVirtual({ idMateria }: Props) {
  const [apuntes, setApuntes] = useState<Apunte[]>([]);
  const [apunteSeleccionado, setApunteSeleccionado] = useState<Apunte | undefined>();

  const [mostrarFormulario, setMostrarFormulario] = useState(false);
  const [modoEdicion, setModoEdicion] = useState(false);
  const [apunteEditando, setApunteEditando] = useState<Apunte | undefined>();

  const [nuevoTitulo, setNuevoTitulo] = useState("");
  const [nuevoResumen, setNuevoResumen] = useState("");

  const [menuVisibleId, setMenuVisibleId] = useState<number | undefined>();

  // 🔹 Cargar apuntes (equivale a ngOnInit)
  useEffect(() => {
    listarApuntes(idMateria)
      .then(data => {
        setApuntes(data);
        if (data.length > 0) {
          setApunteSeleccionado(data[0]);
        }
      })
      .catch(err => console.error(err));
  }, [idMateria]);

  // 🔹 Cerrar menú contextual al hacer click fuera
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const target = event.target as HTMLElement;
      if (!target.closest(".menu-apunte")) {
        setMenuVisibleId(undefined);
      }
    }

    document.addEventListener("click", handleClickOutside);
    return () => document.removeEventListener("click", handleClickOutside);
  }, []);

  // 🔹 Helpers
  function resetFormulario() {
    setNuevoTitulo("");
    setNuevoResumen("");
    setModoEdicion(false);
    setApunteEditando(undefined);
  }

  function toggleFormulario() {
    setMostrarFormulario(!mostrarFormulario);
    if (mostrarFormulario) resetFormulario();
  }

  // 🔹 CRUD
  async function crear() {
    if (!nuevoTitulo.trim()) return;

    const apunte = await insertarApunte(idMateria, {
      titulo: nuevoTitulo.trim(),
      resumen: nuevoResumen.trim()
    });

    setApuntes([apunte, ...apuntes]);
    setApunteSeleccionado(apunte);
    toggleFormulario();
  }

  async function guardarCambios() {
    if (!apunteEditando) return;

    const actualizado = {
      ...apunteEditando,
      titulo: nuevoTitulo.trim(),
      resumen: nuevoResumen.trim()
    };

    await modificarApunte(actualizado);

    setApuntes(apuntes.map(a => a.idApunte === actualizado.idApunte ? actualizado : a));
    setApunteSeleccionado(actualizado);
    toggleFormulario();
  }

  async function eliminar(apunte: Apunte) {
    await eliminarApunte(apunte.idApunte);
    const nuevos = apuntes.filter(a => a.idApunte !== apunte.idApunte);
    setApuntes(nuevos);
    setApunteSeleccionado(nuevos[0]);
  }

  return (
    <div className="cuaderno-container">
      <div className="sidebar">
        <h3>Mis Apuntes</h3>

        <button className="nuevo-btn" onClick={toggleFormulario}>
          {mostrarFormulario ? "Cancelar" : modoEdicion ? "Editar apunte" : "+ Nuevo apunte"}
        </button>

        {mostrarFormulario && (
          <div className="formulario-nuevo">
            <input
              placeholder="Título"
              value={nuevoTitulo}
              onChange={e => setNuevoTitulo(e.target.value)}
            />
            <textarea
              placeholder="Resumen (opcional)"
              value={nuevoResumen}
              onChange={e => setNuevoResumen(e.target.value)}
            />
            <button onClick={modoEdicion ? guardarCambios : crear} disabled={!nuevoTitulo.trim()}>
              {modoEdicion ? "Guardar cambios" : "Guardar apunte"}
            </button>
          </div>
        )}

        <div className="lista-apuntes">
          {apuntes.map(apunte => (
            <div
              key={apunte.idApunte}
              className={`item-apunte ${apunteSeleccionado?.idApunte === apunte.idApunte ? "seleccionado" : ""}`}
            >
              <div className="apunte-info" onClick={() => setApunteSeleccionado(apunte)}>
                <h4 title={apunte.titulo}>{apunte.titulo}</h4>
                {apunte.resumen && <p title={apunte.resumen}>{apunte.resumen}</p>}
              </div>

              <div className="menu-apunte">
                <button className="btn-menu" onClick={() => setMenuVisibleId(apunte.idApunte)}>⋯</button>

                {menuVisibleId === apunte.idApunte && (
                  <div className="menu-opciones">
                    <button onClick={() => {
                      setModoEdicion(true);
                      setApunteEditando(apunte);
                      setNuevoTitulo(apunte.titulo);
                      setNuevoResumen(apunte.resumen || "");
                      setMostrarFormulario(true);
                      setMenuVisibleId(undefined);
                    }}>
                      ✏️ Editar apunte
                    </button>
                    <button onClick={() => eliminar(apunte)}>
                      🗑️ Eliminar apunte
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="contenido">
        {apunteSeleccionado ? (
          <ContenidoApunte apunte={apunteSeleccionado} />
        ) : (
          <p className="mensaje-seleccion">
            Selecciona un apunte para comenzar.
          </p>
        )}
      </div>
    </div>
  );
}

// proyecto-frontend/src/app/components/cuaderno-virtual/cuaderno-virtual.component.ts
import { Component, OnInit, HostListener } from '@angular/core';
import { Apunte, ApunteService } from '../../services/apunte.service';
import { ActivatedRoute } from '@angular/router';
import { Materia, MateriaService } from '../../services/materia.service';

@Component({
  selector: 'app-cuaderno-virtual',
  standalone: false,
  templateUrl: './cuaderno-virtual.component.html',
  styleUrl: './cuaderno-virtual.component.css'
})

export class CuadernoVirtualComponent implements OnInit {
  idMateria!: number;
  apuntes: Apunte[] = [];
  apunteSeleccionado?: Apunte;
  modalVisible: boolean = false;
  modalTitulo: string = '';
  modalMensaje: string = '';
  apuntePendiente?: Apunte;
  materiaSeleccionada?: Materia;

  mostrarFormulario: boolean = false;
  nuevoTitulo: string = '';
  nuevoResumen: string = '';

  modoEdicion: boolean = false;
  apunteEditando?: Apunte;
  menuVisibleId?: number;

  constructor(
    private apunteService: ApunteService,
    private materiaService: MateriaService,
    private route: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this.idMateria = Number(this.route.snapshot.paramMap.get('id'));
    this.obtenerMateria();
    this.cargarApuntes();
  }

  obtenerMateria(): void {
    this.materiaService.getMaterias().subscribe({
      next: (materias) => {
        this.materiaSeleccionada = materias.find(m => m.idMateria === this.idMateria);
      },
      error: (err) => console.error('Error al obtener materia:', err)
    });
  }

  cargarApuntes(): void {
    this.apunteService.listarApuntes(this.idMateria).subscribe({
      next: (data) => {
        this.apuntes = data;
        if (data.length > 0) {
          this.seleccionarApunte(data[0]);
        }
      },
      error: (err) => console.error('Error al listar apuntes:', err)
    });
  }

  toggleFormulario(): void {
    this.mostrarFormulario = !this.mostrarFormulario;
    if (!this.mostrarFormulario) this.resetFormulario();
  }

  resetFormulario(): void {
    this.nuevoTitulo = '';
    this.nuevoResumen = '';
    this.apunteEditando = undefined;
    this.modoEdicion = false;
  }

  crearApunte(): void {
    if (!this.nuevoTitulo.trim()) return;

    const nuevo: Partial<Apunte> = {
      titulo: this.nuevoTitulo.trim(),
      resumen: this.nuevoResumen.trim()
    };

    this.apunteService.insertarApunte(nuevo, this.idMateria).subscribe({
      next: (apunte) => {
        this.apuntes.unshift(apunte);
        this.seleccionarApunte(apunte);
        this.toggleFormulario();
      },
      error: (err) => console.error('Error al crear apunte:', err)
    });
  }

  editarApunte(apunte: Apunte): void {
    this.modoEdicion = true;
    this.apunteEditando = apunte;
    this.nuevoTitulo = apunte.titulo;
    this.nuevoResumen = apunte.resumen || '';
    this.mostrarFormulario = true;
    this.menuVisibleId = undefined;
  }

  guardarCambios(): void {
    if (!this.apunteEditando || !this.nuevoTitulo.trim()) return;

    const actualizado: Apunte = {
      ...this.apunteEditando,
      titulo: this.nuevoTitulo.trim(),
      resumen: this.nuevoResumen.trim()
    };

    this.apunteService.modificarApunte(actualizado).subscribe({
      next: () => {
        const index = this.apuntes.findIndex(a => a.idApunte === actualizado.idApunte);
        if (index !== -1) {
          this.apuntes[index] = actualizado;
          this.seleccionarApunte(actualizado);
        }
        this.toggleFormulario();
        this.resetFormulario();
      },
      error: (err) => console.error('Error al modificar apunte:', err)
    });
  }

  confirmarEliminar(apunte: Apunte): void {
    this.apuntePendiente = apunte;
    this.modalTitulo = 'Confirmar eliminación';
    this.modalMensaje = '¿Estás seguro que deseas eliminar este apunte? Se eliminará todo el contenido que contiene.';
    this.modalVisible = true;
    this.menuVisibleId = undefined;
  }

  eliminarConfirmado(): void {
    if (!this.apuntePendiente) return;

    this.apunteService.eliminarApunte(this.apuntePendiente.idApunte).subscribe({
      next: () => {
        this.apuntes = this.apuntes.filter(a => a.idApunte !== this.apuntePendiente?.idApunte);
        if (this.apunteSeleccionado?.idApunte === this.apuntePendiente?.idApunte) {
          this.apunteSeleccionado = this.apuntes[0] || undefined;
        }
        this.modalVisible = false;
        this.apuntePendiente = undefined;
      },
      error: (err) => console.error('Error al eliminar apunte:', err)
    });
  }

  cancelarEliminacion(): void {
    this.modalVisible = false;
    this.apuntePendiente = undefined;
  }

  seleccionarApunte(apunte: Apunte): void {
    this.apunteSeleccionado = apunte;
    this.menuVisibleId = undefined;
  }

  toggleMenu(id: number): void {
    this.menuVisibleId = this.menuVisibleId === id ? undefined : id;
  }

  @HostListener('document:click', ['$event'])
  cerrarMenusFuera(event: Event) {
    const clickedInside = (event.target as HTMLElement).closest('.menu-apunte');
    if (!clickedInside) this.menuVisibleId = undefined;
  }
}

<div class="cuaderno-container">
  <div class="sidebar">
    <h3>Mis Apuntes <span *ngIf="materiaSeleccionada">– {{ materiaSeleccionada.nombreMateria }}</span></h3>
    <button class="nuevo-btn" (click)="toggleFormulario()">
      {{ mostrarFormulario ? 'Cancelar' : (modoEdicion ? 'Editar apunte' : '+ Nuevo apunte') }}
    </button>

    <div class="formulario-nuevo" *ngIf="mostrarFormulario">
      <input type="text" placeholder="Título" [(ngModel)]="nuevoTitulo" />
      <textarea placeholder="Resumen (opcional)" [(ngModel)]="nuevoResumen"></textarea>
      <button (click)="modoEdicion ? guardarCambios() : crearApunte()" [disabled]="!nuevoTitulo.trim()">
        {{ modoEdicion ? 'Guardar cambios' : 'Guardar apunte' }}
      </button>
    </div>

    <div class="lista-apuntes">
      <div *ngFor="let apunte of apuntes" class="item-apunte" [class.seleccionado]="apunte === apunteSeleccionado">
        <div class="apunte-info" (click)="seleccionarApunte(apunte)">
          <h4 [title]="apunte.titulo">{{ apunte.titulo }}</h4>
          <p *ngIf="apunte.resumen" [title]="apunte.resumen">{{ apunte.resumen }}</p>
        </div>

        <div class="menu-apunte">
          <button class="btn-menu" (click)="toggleMenu(apunte.idApunte)">⋯</button>

          <div class="menu-opciones" *ngIf="menuVisibleId === apunte.idApunte">
            <button (click)="editarApunte(apunte)">✏️ Editar apunte</button>
            <button (click)="confirmarEliminar(apunte)">🗑️ Eliminar apunte</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="contenido">
    <ng-container *ngIf="apunteSeleccionado; else mensaje">
      <app-contenido-apunte [apunte]="apunteSeleccionado"></app-contenido-apunte>
    </ng-container>

    <ng-template #mensaje>
      <p class="mensaje-seleccion">Selecciona un apunte para comenzar.</p>
    </ng-template>
  </div>
</div>

<app-modal-confirmacion
  [visible]="modalVisible"
  [titulo]="modalTitulo"
  [mensaje]="modalMensaje"
  (aceptar)="eliminarConfirmado()"
  (cancelar)="cancelarEliminacion()">
</app-modal-confirmacion>
